name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Pyinstaller
      uses: nicolaschan/pyinstaller-action@v2
      with:
        input: bofhbot.py
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: bofhbot
        path: dist/bofhbot
    
